name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-16.04,ubuntu-18.04, ubuntu-latest]
        target: [k1-unknown-elf, k1-unknown-linux-uclibc]

    runs-on: ${{ matrix.os }}
   
    steps:
    - uses: actions/checkout@v1
    - name: Install packages
      run: sudo apt-get install bison flex libncurses5-dev texinfo help2man g++ libtool-bin
    - name: Configure CTNG
      run: ./bootstrap && ./configure --enable-local
    - name: Build CTNG
      run: make
    - name: Configure ${{ matrix.target }}
      run: ./ct-ng ${{ matrix.target }}
    - name: Build ${{ matrix.target }}
      run: ./ct-ng build
